### ISSUE TITLE
Private key of user should not be copied to the master server

### ISSUE THREAD

**Issue by sascha-egerer** [rgardler/acs-cli#11]
Currently the private key of the user executing the script (and suppose the key is stored under ~/.ssh/id_rsa) is copied to the master server.
https://github.com/rgardler/acs-scripts/blob/6fe5798fa6b19cbb0daa82db1698a724b981bef2/acs/acs_utils.py#L214-L220

IMHO this is really... not a good idea...

What about creating an seperate key or at least let the user define a key that should be used

**Comment by rgardler** [comment]
You are absolutely correct.

I should put A VERY big warning on this saying NOT FOR PRODUCTION. I was being very lazy and just wanted to get things working. 

What we should be doing is using "ssh -A" in the connection from client to master (at least if I understand that switch correctly, I'm no SSH expert). Even that is not ideal, but it's better than copying private keys.

A longer term solution would be to have ACS create the keys as you suggest. These scripts are intended to bridge gaps in ACS, but that's no excuse for this kind of thing,

**Comment by rgardler** [comment]
Looking into the options here it seems agent forwarding is the way to go (though I've not tested yet). See this guide http://www.unixwiz.net/techtips/ssh-agent-forwarding.html (until such a time as the cluster has keys automatically configured)

To enable the client machine must have the following in their ~/.ssh/config

Host example.com
  ForwardAgent yes

**Comment by teelahti** [comment]
Other related issue is that currently the script assumes default id_rsa key is used: 

        localfile = home + "/.ssh/id_rsa"

Many times people have multiple keys. The key file path should probably be in the configuration file.

**Comment by rgardler** [comment]
As part of the work on Issue #20 I've now resolved this (see branch "pluggable_cli") I'm leaving this open until that branch is merged with master.

**Comment by rgardler** [comment]
Fix is now merged
