### ISSUE TITLE
Adding features fails due to management endpoint not publicly accessible right after deployment

### ISSUE THREAD

**Issue by teelahti** [rgardler/acs-cli#18]
Currently the deploy-command first deploys cluster, and then right after adds features to it. Unfortunately there is a delay in Azure DNS that causes feature adding to fail as the management endpoint is not resolving for a while. Probably needs a polling mechanism to wait for the endpoint.

**Comment by rgardler** [comment]
This has been refactored, features are not automatically added at this time so this problem has gone away.
