### ISSUE TITLE
acs create doesn't automatically login

### ISSUE THREAD

**Issue by rbitia** [rgardler/acs-cli#53]
acs service create
....
..
.info:    Executing command group create
error:   There is no current subscription. Please use the azure login command to set your current subscription.
error:   Error information has been recorded to /root/.azure/azure.err
error:   group create command failed

2016-08-09 00:13:22,718 - Config - DEBUG - Checking if public SSH key exists: /root/.ssh/id_rsa.pub
info:    Executing command group deployment create
error:   There is no current subscription. Please use the azure login command to set your current subscription.
error:   Error information has been recorded to /root/.azure/azure.err
error:   group deployment create command failed

**Comment by rgardler** [comment]
Fixed.

**Comment by underwindfall** [comment]
Could u tell me how to fixed it i have same problem

**Comment by rgardler** [comment]
The issue this reported to is fixed in the code. If you are still seeing the symptoms describe please raise another issue with repro instructions.
