### ISSUE TITLE
how do I

### ISSUE THREAD

**Issue by rbitia** [rgardler/acs-cli#56]
def test_open(self, lb):
        starttime = time.time()
        lb.args = {'--port': '32123'}

        result = lb.open()
        endtime = time.time()

        lb.log.info("Total time to open port: " + str((endtime - starttime)/60) + " minutes")

        assert('Opened port 32123' in result)
That's the lb code but what command should I use to open a port in my new elkstack command??
Do I need to make a new definition in my code open_post(self, lb)?

**Comment by rbitia** [comment]
#open ports in azure
      open(5601)
      open(9200)
     # marathon load balancer
      self.shell.something(dcos package install marathon-lb)
^^ I'm trying to open ports and install the marathon-lb in this code

**Comment by rbitia** [comment]
lb = Lb(self.config, None)
      lb.args = {"--port": 5601}
      lb.open()
      lb.args = {"--port": 9200}
      lb.open()
      # marathon load balancer
      self.shell_execute("dcos package install marathon-lb --yes")

**Comment by rgardler** [comment]
Thanks for answering your own question :-)

---
Twitter: @rgardler

________________________________
