### ISSUE TITLE
authentication exception error 

### ISSUE THREAD

**Issue by rbitia** [rgardler/acs-cli#59]
I got that error from yesterday again... 
 raise AuthenticationException("Unable to connect to SSH agent")
paramiko.ssh_exception.AuthenticationException: Unable to connect to SSH agent

Forgot the fix though :( Wasn't this going to be fixed when I merged with the dev branch before?? Did I miss a step that would have fixed this?

**Comment by rgardler** [comment]
This is fixed in the dev branch, but you need to rebuild your container for it to take effect.
