### ISSUE TITLE
Add Autoscale rules configuration

### ISSUE THREAD

**Issue by rgardler** [rgardler/acs-cli#6]
In the future the LinuxDiagnostics extension will be installed on agents by default, but at the time of writing it is not. This means AutoScale on the Agents is difficult to set-up.

We need to add commands to scale an agent pool up/down as well as add a feature to install the LinuxDiagnostics Extension

**Comment by rgardler** [comment]
I can't seem to find a way to install the Linux Diagnostics Extension on an existing VMSS. Looking into it further.

**Comment by rgardler** [comment]
Linux diagnostics is now supported in ACS, but autoscale rules are not.

**Comment by milan-dasek** [comment]
Hello,

Do you know when VMMS auto scale will be ready for customers? It is a blocker for us now.

Thank you

Milan Dasek

**Comment by rgardler** [comment]
They will work today. There is no ACS specific CLI to manage this at this time, but all methods to build out rules for the underlying VMSS will work.

I'd gladly help you get this into this unofficial CLI tool but have no plans to add it myself.
