### ISSUE TITLE
If no 'acs' container has ever been started dev-docker.sh fails

### ISSUE THREAD

**Issue by rbitia** [rgardler/acs-cli#60]
./scripts/dev-docker.sh: line 11: [: <no value>: integer expression expected
Re-starting and connecting to an 'acs' container
Error response from daemon: no such id: acs
FATA[0000] Error: failed to start one or more containers
FATA[0000] Error response from daemon: no such id: acs

**Comment by rgardler** [comment]
I think the title is wrong, the problem here is that if a container called 'acs' has not previously been started then it fails.

This is a bug in the dev-docker.sh script that looks for a pre-existing container.
